#This Docker file is based on https://github.com/ot4i/ace-docker

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6 as builder

RUN microdnf update && microdnf install util-linux curl tar

ARG USERNAME
ARG PASSWORD

#check latest ACE developer from http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/integration/
ARG DOWNLOAD_URL=http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/integration/12.0.4.0-ACE-LINUX64-DEVELOPER.tar.gz

RUN mkdir -p /opt/ibm/ace-12 \
    && if [ -z $USERNAME ]; then curl ${DOWNLOAD_URL}; else curl -u "${USERNAME}:${PASSWORD}" ${DOWNLOAD_URL}; fi | \
    tar zx --absolute-names \
    --exclude ace-12.0.*.0/tools \
    --exclude ace-12.0.*.0/server/tools/ibm-dfdl-java.zip \
    --exclude ace-12.0.*.0/server/tools/proxyservlet.war \
    --exclude ace-12.0.*.0/server/bin/TADataCollector.sh \
    --exclude ace-12.0.*.0/server/transformationAdvisor/ta-plugin-ace.jar \
    --strip-components 1 \
    --directory /opt/ibm/ace-12

#create base image
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6

#update/install packages
RUN microdnf update && \ 
    microdnf install findutils util-linux curl tar && \
    microdnf clean all && \
    microdnf reinstall tzdata -y
# Note: force reinstall tzdata package to get zoneinfo files

#copy ACE from builder
COPY --from=builder /opt/ibm/ace-12 /opt/ibm/ace-12

#accept license
ENV LICENSE=accept
ENV ACE_WORKING_DIR=/home/aceuser/ace-server

RUN /opt/ibm/ace-12/ace make registry global accept license deferred \
    && useradd --uid 1001 --create-home --home-dir /home/aceuser --shell /bin/bash -G mqbrkrs aceuser \
    && su - aceuser -c "export LICENSE=accept && . /opt/ibm/ace-12/server/bin/mqsiprofile && mqsicreateworkdir $ACE_WORKING_DIR" \
    && echo ". /opt/ibm/ace-12/server/bin/mqsiprofile" >> /home/aceuser/.bashrc

WORKDIR /home/aceuser

# Add required license as text file in Licenses directory (GPL, MIT, APACHE, Partner End User Agreement, etc)
COPY licenses/ ./licenses/

#add integration application sources
COPY ace-sample-app/ ./src/

COPY start.sh .

# Expose ports.  7600, 7800, 7843 for ACE.
EXPOSE 7600 7800 7843

#change ownership of all files
RUN chown -R 1001 /home/aceuser

# run as aceuser
USER 1001

CMD ["/bin/sh","start.sh"]
